{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "orders-service.fullname" . }}
  labels:
    {{- include "orders-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "orders-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- range .Values.networkPolicy.allowedIngress }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
        {{- end }}
  egress:
    - to:
        {{- range .Values.networkPolicy.allowedEgress }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
        {{- end }}
{{- end }}
