apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orders-service.fullname" . }}-secrets
  annotations:
    {{- if .Values.vault.enabled }}
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: orders-service
    vault.hashicorp.com/agent-inject-secret-orders-env: {{ .Values.vault.path }}
    {{- end }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.env.databaseUrl | quote }}
